Ajax2
BubuntuClu/questionTime pull request #16
Opened 2017-01-18 13:32 UTC by BubuntuClu

2017-01-18 13:33 UTC, BubuntuClu commented on spec/acceptance/edit_answer_spec.rb
> +      save_and_open_page
Не могу понять, почему в этот момент не видно ссылку на редактирование.

2017-01-18 15:08 UTC, vkurennov requested changes

2017-01-18 15:08 UTC, vkurennov commented on app/views/questions/_answers.html.slim
> +-@question.answers.each do |answer|
Вспоминай анонимные паршалы, тут можно просто render @question.answers написать. Но тогда и смысл в этом паршале отпадает

2017-01-18 15:08 UTC, vkurennov commented on spec/acceptance/edit_answer_spec.rb
> +      save_and_open_page
Внимательно посмотри на свои виды. В каком случае у тебя не выводится ссылка на редактирование? Если это не залогиненный юзер или он не автор. Первый вариант не подходит, т.к. есть sign_in, значит второй. Где у тебя связь между ответом и залогиненным юзером? Ее нет, т.к. ответ ты создаешь с другим, автоматически сгенерированным и назначенным юзером (а вот связь вопроса и ответа есть).

2017-01-19 17:24 UTC, vkurennov requested changes

2017-01-19 17:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:q_id])
1. Всю логику по установке лучшего ответа нужно инкапсулировать в методе модели Answer, а здесь только вызывать его. В контроллерах не должно быть бизнес-логики (логики, меняющей состояние системы).
2. Т.к. у тебя несколько изменений может проходить, нужно их обернуть в [транзакцию](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html).

2017-01-19 17:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:a_id])
Почему параметр называется  :a_id? Ведь если будет обычный вложенный роутинг, то у тебя  будут параметры :question_id  и :id

2017-01-19 17:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.save
Опасно по-отдельности обновлять данные, если они должны обновиться вместе. Вдруг со старого ответа снимется метка лучшего, а при обновлении нового что-то произойдет? Тогда новый ответ не станет лучшим. Поэтому надо применять транзакции.

2017-01-19 17:24 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      old_best.save
Используй метод update, чтобы и установить атрибут и сохранить его.

2017-01-19 17:24 UTC, vkurennov commented on app/views/answers/_answer.html.slim
> +      =link_to 'Mark as best', mark_best_answers_path(a_id: answer, q_id: answer.question), class: 'mark-best-answer-link', data: { answer_id: answer.id }, remote: true
Не надо передавать свои параметры, достаточно сделать кастомный экшн у вложенного ресурса answers в роутинге и вызов будет такой: `mark_best_answers_path(answer.question, answer)`. А если ресурс answers объявить как shallow, то и вопрос передавать не придется.

2017-01-19 17:24 UTC, vkurennov commented on app/views/questions/_answers.html.slim
> +-@question.answers.each do |answer|
Зачем вообще нужен этот паршл, когда можно писать просто `render @question.answers`?

2017-01-19 17:24 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  = render @question.answers.ordered
Вот же вызов рендера списка, так зачем тебе паршл question/_answers?

2017-01-19 17:24 UTC, vkurennov commented on config/routes.rb
> +      get :mark_best
Это метод не коллекции, а элемента коллекции (member), и  именно поэтому надо передавать id. То есть, если передаем id объекта, то это метод member, а если id не нужен (как например, для index, create, new), то это метод collection

2017-01-19 17:24 UTC, vkurennov commented on spec/acceptance/best_answer_spec.rb
> +        expect(page).to have_link 'Mark as best'
Не нужно писать сценарии просто на проверку того, что юзер видит ссылку. Когда в следующем тесте мы на нее кликаем, это неявно проверят, что ссылка есть на странице

2017-01-19 17:24 UTC, vkurennov commented on spec/acceptance/edit_answer_spec.rb
> +        expect(page).to have_link 'Edit'
Опять же лишний тест, в следующем мы кликаем по этой ссылке, тем самым проверяя и ее наличие на странице

2017-01-19 17:24 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      xhr :get, :mark_best, params: { q_id: question, a_id: answer }, format: :js
Более полные тесты должны быть для метода модели Answer, устанавливающего лучший ответ. Ведь там не только устанавливается лучший ответ, а еще и снимается флаг со старого ответа, если он есть. Но все это должно быть в тестах модели

2017-01-20 06:52 UTC, BubuntuClu commented on app/views/answers/_answer.html.slim
> +      =link_to 'Mark as best', mark_best_answers_path(a_id: answer, q_id: answer.question), class: 'mark-best-answer-link', data: { answer_id: answer.id }, remote: true
+

2017-01-20 06:52 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.find(params[:a_id])
+

2017-01-20 06:59 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:q_id])
+

2017-01-20 06:59 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +      old_best.save
+

2017-01-20 06:59 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer.save
+

2017-01-20 07:01 UTC, BubuntuClu commented on app/views/questions/_answers.html.slim
> +-@question.answers.each do |answer|
+

2017-01-20 07:02 UTC, BubuntuClu commented on config/routes.rb
> +      get :mark_best
+

2017-01-20 07:04 UTC, BubuntuClu commented on spec/acceptance/edit_answer_spec.rb
> +        expect(page).to have_link 'Edit'
Но это ведь код из скринкаста? в нем изменения не вносил, оставлял, как подавалось.

2017-01-20 07:22 UTC, BubuntuClu commented on spec/controllers/answers_controller_spec.rb
> +      xhr :get, :mark_best, params: { q_id: question, a_id: answer }, format: :js
+

2017-01-20 07:23 UTC, BubuntuClu commented on spec/acceptance/best_answer_spec.rb
> +        expect(page).to have_link 'Mark as best'
+

2017-01-20 10:03 UTC, vkurennov commented on spec/acceptance/edit_answer_spec.rb
> +        expect(page).to have_link 'Edit'
Да, действительно. Значит, еще одна ошибка закралась в скринкаст :-) В общем, особого смысла так делать нет. Учти на будущее

2017-01-20 10:13 UTC, vkurennov requested changes

2017-01-20 10:13 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    Answer.set_best_answer(@question, @answer)
У тебя есть конкретный объект @answer, так почему ты пишешь метод класса и передаешь туда этот объект, когда можно написать инстанс-метод и вызвать метод у объекта?

2017-01-20 10:13 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:question_id])
Объяви ресурс answers как shallow (в роутах) и тогда не придется загружать вопрос (и передавать его), т.к. его можно взять из ассоциаций ответа

2017-01-20 10:13 UTC, vkurennov commented on app/models/answer.rb
> +      old_best.update_attribute(:best, false) unless old_best.blank?
Транзакция откатывается только если было выброшено исключеие, поэтому, для  изменения надо использовать метод `update!`, который как раз выкидывает исключение, если обновление не прошло.

2017-01-20 10:13 UTC, vkurennov commented on config/routes.rb
> +    resources :answers do
Объяви этот ресурс как shallow, чтобы не передавать вопрос там, где этого не требуется

2017-01-20 10:13 UTC, vkurennov commented on config/routes.rb
> +        get :mark_best
get-запросы не должны изменять данные. Это должен быть post или put/patch запрос.

2017-01-20 10:13 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      xhr :get, :mark_best, params: { q_id: question, a_id: answer }, format: :js
По-моему, этот тест не совсем акутальный теперь. Ведь ты же используешь id и question_id в контроллере, причем тут параметры q_id и a_id?

2017-01-20 10:13 UTC, vkurennov commented on app/models/answer.rb
> +  def self.set_best_answer(question, answer)
Ты же работаешь с конкретным объетом и изменяешь конкретный объект. Так почему это метод класса, а не объекта?

2017-01-20 10:13 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +      expect(assigns(:answer).best).to eq(true)
`expect(assigns(:answer)).to be_best`

2017-01-20 10:13 UTC, vkurennov commented on spec/models/answer_spec.rb
> +    before { @user = create(:user) }
Зачем через before создавать юзера, чем обычный let/let!  не подошел?

2017-01-20 10:13 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.reload.best).to eq(true)
`expect(answer.reload).to be_best`

Это фича рспека: он умеет создавать динамические матчеры для методов-предикатов (заканчиваются на знак вопроса) и булевых атрибутов

2017-01-20 10:13 UTC, vkurennov commented on spec/models/answer_spec.rb
> +      expect(answer.reload.best).to eq(false)
expect(answer.reload).to_not be_best

2017-01-20 11:18 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @question = Question.find(params[:question_id])
+

2017-01-20 11:18 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    Answer.set_best_answer(@question, @answer)
+

2017-01-20 11:18 UTC, BubuntuClu commented on app/models/answer.rb
> +  def self.set_best_answer(question, answer)
+

2017-01-20 11:18 UTC, BubuntuClu commented on app/models/answer.rb
> +      old_best.update_attribute(:best, false) unless old_best.blank?
+

2017-01-20 11:18 UTC, BubuntuClu commented on config/routes.rb
> +    resources :answers do
+

2017-01-20 11:18 UTC, BubuntuClu commented on config/routes.rb
> +        get :mark_best
+

2017-01-20 11:18 UTC, BubuntuClu commented on spec/controllers/answers_controller_spec.rb
> +      expect(assigns(:answer).best).to eq(true)
+

2017-01-20 11:19 UTC, BubuntuClu commented on spec/models/answer_spec.rb
> +    before { @user = create(:user) }
В принципе тут можно вообще от юзера отказаться в этих спеках. Т.к. пока нет проверки на конкретного пользователя

2017-01-20 11:19 UTC, BubuntuClu commented on spec/models/answer_spec.rb
> +      expect(answer.reload.best).to eq(true)
+

2017-01-20 11:19 UTC, BubuntuClu commented on spec/models/answer_spec.rb
> +      expect(answer.reload.best).to eq(false)
+

2017-01-20 14:51 UTC, vkurennov approved these changes

2017-01-20 14:51 UTC, vkurennov commented on app/models/answer.rb
> +      old_best.update!(best: false) unless old_best.blank?
Условие лучше записать как  `if old_best`

2017-01-20 17:09 UTC, merged