Ajax3
BubuntuClu/questionTime pull request #18
Opened 2017-02-01 16:33 UTC by BubuntuClu

2017-02-02 08:58 UTC, vkurennov requested changes

2017-02-02 08:58 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +      updated_rating = obj.rating + vote_params[:value].to_i
Слишком много логики в контроллере, нужно выносить это в модели (или консерны моделей).

2017-02-02 08:58 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +      updated_rating = obj.rating + vote_params[:value].to_i
Нельзя передавать в параметрах значение голоса, т.к. легко будет делать накрутку, например, передав там +100500. А голоса должны изменяться ровно на 1.

2017-02-02 08:58 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +            render json: { id: "#{obj.class.name.underscore}_#{obj.id}", rating: obj.rating, action: "vote" }
Если у тебя только один формат ответа (json), то не нужно все оборачивать в блок respond_to

2017-02-02 08:58 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +      updated_rating = obj.rating - vote.value.to_i
И опять же бизнес-логика в контроллере, а контроллер не должен ничего менять, он просто вызывает нужный метод у нужной модели и все. Вся логика должна быть в модели.

2017-02-02 08:58 UTC, vkurennov commented on app/models/question.rb
> +  has_many :votes, as: :votable
Вот это можно было бы вынести в консерн, как и аттачменты и таким образом избавиться от дублирования.

2017-02-02 08:58 UTC, vkurennov commented on config/routes.rb
> +  resources :votes, only: [:create, :destroy]
Сделай ресурс вложенным в вопросы/ответы, тогда не надо будет передавать тип и id объекта, все можно будет взять из параметров запроса и url

2017-02-02 08:58 UTC, vkurennov commented on app/views/votes/_votes.html.slim
> +    div #{link_to 'Vote up', votes_path( vote: {votable_id: obj, votable_type: obj.class.name, value: 1 }), method: 'post', remote: true, format: :json, class: "vote_up #{obj.votes.where(users_id: cu
Используй вложенные ресурсы, чтобы не передавать votable_id и votable_type. Ну и значение голоса не должно приходить из паарметров.

2017-02-02 10:23 UTC, BubuntuClu commented on app/controllers/votes_controller.rb
> +            render json: { id: "#{obj.class.name.underscore}_#{obj.id}", rating: obj.rating, action: "vote" }
+

2017-02-02 10:49 UTC, BubuntuClu commented on config/routes.rb
> +  resources :votes, only: [:create, :destroy]
Не совсем понял как достать класс в таком случае.
Если сделать вложенным ресурс, то у нас получается два genb question_votes_path и answer_votes path. Уже больше логики во вьюхе будет для определения какой путь вызывать. Так же в этом случае передается только сам объект, который имеет параметр "answer/question_id". Из этого параметра выкусывать класс объекта?

2017-02-02 16:26 UTC, vkurennov commented on config/routes.rb
> +  resources :votes, only: [:create, :destroy]
Да, из url получить и тип объект и id, дел на 2 строки кода. Вот посмотри здесь, например: https://rubyplus.com/articles/3901-Polymorphic-Association-in-Rails-5

2017-02-02 16:32 UTC, vkurennov requested changes

2017-02-02 16:32 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +      if vote.persisted?
Тут надо двойную проверку: если объект валидный и сохранен. Т.к. если он не сохранен, это еще не значит, что он не валидный

2017-02-02 16:32 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    if !current_user.author_of?(obj)
А вот здесь неверная проверка. Наоборот, голос может удалить только тот, кто его создал, т.е. автор **голоса** (не вопроса/ответа)

2017-02-02 16:32 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    updated_rating = self.rating + 1
Зачем вычислять рейтинг заранее? А если за это время какой-то еще голос будет добавлен. Лучше уже в транзакции обновить значение рейтинга.

2017-02-02 16:32 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    updated_rating = self.rating - 1
То же самое: лучше менять рейтинг как можно  "ближе" к апдейту

2017-02-02 16:32 UTC, vkurennov commented on app/models/concerns/votable.rb
> +    updated_rating = self.rating - vote.value.to_i
Тут лучше по-другому сделать: пересчитать сумму всех голосов за объект и ее уже сохранить, т.к. может оказаться, что пока идут запросы кто-то еще создал или удалил голос. Ну и тоже это надо делать внутри тарнзакции и update

2017-02-02 16:34 UTC, BubuntuClu commented on config/routes.rb
> +  resources :votes, only: [:create, :destroy]
вот теперь понятно

2017-02-02 18:23 UTC, BubuntuClu commented on config/routes.rb
> +  resources :votes, only: [:create, :destroy]
Так, для create у меня получилось. Но для delete у меня ересь какая-то творится. Для question ссылка на удаление vote_path, а для answer - answer_votes_path. Пока вынес метод destroy в отдельный ресурс. Может я не так вложенность сделал?

2017-02-02 18:26 UTC, BubuntuClu commented on app/models/concerns/votable.rb
> +    updated_rating = self.rating - vote.value.to_i
+

2017-02-02 18:29 UTC, BubuntuClu commented on app/models/concerns/votable.rb
> +    updated_rating = self.rating - 1
+

2017-02-02 18:29 UTC, BubuntuClu commented on app/models/concerns/votable.rb
> +    updated_rating = self.rating + 1
+

2017-02-02 18:34 UTC, BubuntuClu commented on config/routes.rb
> +    resources :votes, only: [:create], shallow: true
https://github.com/BubuntuClu/questionTime/pull/18#discussion-diff-99074105R13

2017-02-02 18:34 UTC, BubuntuClu commented on config/routes.rb
> +    resources :votes, only: [:create], shallow: true
описал ситуацию

2017-02-03 09:04 UTC, vkurennov requested changes

2017-02-03 09:04 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    if !current_user.author_of?(obj) && obj.votes.where(users_id: current_user.id).take.users_id == current_user.id
Что-то тут совсем страшное. Тебе в общем-то не важно, является юзер автором объекта или нет, тебе достаточно проверить только то, что юзер является автором голоса. 
И желательно сделать метод, который умел бы у объекта возвращать голос для текущего юезера (ну или nil, если голоса нет). Как раз его можно поместить в консерн моделей

2017-02-03 09:04 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +        render json: obj.errors.full_messages, status: :unprocessable_entity
Это бессмысленно, т.к. валидация при удалении не происходит, и ниакаих ошибок не будет.

2017-02-03 09:04 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    params.require(:vote).permit(:votable_id, :votable_type, :value)
А зачем тут :votable_id, :votable_type, если мы получаем из url эти параметры?

2017-02-03 09:04 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    klass, id = request.path.split('/')[1,2]
Это стоит вынести в метод, чтобы не загромождать экшн

2017-02-03 09:04 UTC, vkurennov commented on config/routes.rb
> +    resources :votes, only: [:create], shallow: true
Вообще, в роутах тоже есть консерный, и это как раз случай, где их надо применить, чтобы не было дублирования.

2017-02-03 09:04 UTC, vkurennov commented on config/routes.rb
> +      resources :votes, only: [:create], shallow: true
И почему только create? Ты же сам пишешь, что у тебя с удалением ересь, так у тебя вообще нет в роутинге пути для destroy, вот поэтому и ересь.

2017-02-03 10:20 UTC, BubuntuClu commented on app/controllers/votes_controller.rb
> +    params.require(:vote).permit(:votable_id, :votable_type, :value)
это для дестроя

2017-02-03 10:47 UTC, BubuntuClu commented on app/controllers/votes_controller.rb
> +    klass, id = request.path.split('/')[1,2]
+

2017-02-03 11:09 UTC, BubuntuClu commented on app/controllers/votes_controller.rb
> +    if !current_user.author_of?(obj) && obj.votes.where(users_id: current_user.id).take.users_id == current_user.id
+

2017-02-04 09:16 UTC, vkurennov requested changes

2017-02-04 09:16 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    params.require(:vote).permit(:votable_id, :votable_type, :value)
Так а зачем передвать эти данные, если он в самом голосе хранятся? Загружаешь голос по id, у него вызываешь ассоциацию commentable, вот тебе и нужный объект. Либо тогда не делай shallow у votes, пусть передается также в url все, и будешь тем же методом, что и в create получать родительский объект

2017-02-04 09:16 UTC, vkurennov commented on app/views/votes/_votes.html.slim
> +    div #{link_to 'Vote up', send("#{obj.class.name.underscore}_votes_path", obj, vote: { value: 'up' }), method: 'post', remote: true, format: :json, class: "vote_up #{obj.votes.where(users_id: curr
Ох, использовать send в видах плохая идея. Используй-ка лучше polymorphic_path
И почему у тебя все в строку записано и через интерполяцию? Пиши номрмально:

```
div
  = link_to ...
  = link_to ...
```

И для получения голоса у объекта лучше сделать метод и его вызывать, например, `obj.vote_for(current_user)`, это гораздо лучше и короче, чем каждый раз where писать.

2017-02-04 11:42 UTC, vkurennov approved these changes

2017-02-07 14:25 UTC, merged