Oauth
BubuntuClu/questionTime pull request #21
Opened 2017-02-14 15:09 UTC by BubuntuClu

2017-02-15 15:36 UTC, vkurennov requested changes

2017-02-15 15:36 UTC, vkurennov commented on app/controllers/confirmations_controller.rb
> +      redirect_to root_path, notice: 'Your email was confirmed. Now u can sign in.'
Редиректы одинаковые, только сообщение меняется, надо бы вынести редирект из условия

2017-02-15 15:36 UTC, vkurennov commented on app/controllers/users_controller.rb
> +    if request.patch? && params[:user]
1. Зачем проверять тип запроса?
2. Что будет, если условие не выполнится (напиши тест на этот кейс, причем тут 2 варианта может быть, почему условие не выполнено).

2017-02-15 15:36 UTC, vkurennov commented on app/controllers/users_controller.rb
> +      @user.send(:generate_confirmation_token)
Зачем тут send, если можно просто метод вызвать? `@user.generate_confirmation_token`. А если это приватный метод, то тогда это костыль. Найди нормальное решение, без вызова приватных методов (например, перенеси логику в модель и вызывай метод модели)

2017-02-15 15:36 UTC, vkurennov commented on app/controllers/users_controller.rb
> +      Devise::Mailer.confirmation_instructions(@user, @user.confirmation_token).deliver_now
Ну в общем-то все это должно быть где-то в модели, т.к. это бизнес-логика, вспоминай теоретическую часть урока про респондеры.

2017-02-15 15:36 UTC, vkurennov commented on app/models/authorization.rb
> +  validates_presence_of :uid, :provider
Что за старые форматы валидаций? Используй нормальный `validates`

2017-02-15 15:36 UTC, vkurennov commented on app/models/user.rb
> +  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
Опять старый формат валидации

2017-02-15 15:36 UTC, vkurennov commented on app/models/user.rb
> +            rescue
А разве тут может быть исключение? И даже если так, не надо перехватывать все исключения, укажи конкретный класс

2017-02-15 15:36 UTC, vkurennov commented on config/routes.rb
> +  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
А почему бы не разделить на 2 разных метода: один с get, который форму показывает, другой - с patch, который отправляет форму.

2017-02-15 15:36 UTC, vkurennov commented on erq
> +
Это что такое?

2017-02-15 15:36 UTC, vkurennov commented on spec/models/authorization_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
Тесты на валидации и ассоциации добавь

2017-02-15 15:36 UTC, vkurennov commented on spec/models/user_spec.rb
> +            expect { User.find_for_oauth(auth) }.to change(user.authorizations, :count).by(1)
А зачем создавть авторизацию, если юзер не сохраняется, согласно предыдущему тесту?

2017-02-15 15:50 UTC, BubuntuClu commented on app/controllers/confirmations_controller.rb
> +      redirect_to root_path, notice: 'Your email was confirmed. Now u can sign in.'
+

2017-02-15 15:57 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +      @user.send(:generate_confirmation_token)
+

2017-02-15 16:01 UTC, BubuntuClu commented on app/models/authorization.rb
> +  validates_presence_of :uid, :provider
+

2017-02-15 16:01 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
+

2017-02-15 16:02 UTC, BubuntuClu commented on erq
> +
+

2017-02-15 16:03 UTC, BubuntuClu commented on spec/models/authorization_spec.rb
> +  pending "add some examples to (or delete) #{__FILE__}"
+

2017-02-15 16:05 UTC, BubuntuClu commented on spec/models/user_spec.rb
> +            expect { User.find_for_oauth(auth) }.to change(user.authorizations, :count).by(1)
Пользователь уже существует, поэтому мы его не создаем, но авторизацию создаем, т.к. ее нет

2017-02-15 16:05 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +      Devise::Mailer.confirmation_instructions(@user, @user.confirmation_token).deliver_now
+

2017-02-15 16:10 UTC, BubuntuClu commented on config/routes.rb
> +  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
от get вообще можно избавиться

2017-02-15 16:15 UTC, BubuntuClu commented on app/models/user.rb
> +            rescue
Оно в тестах происходит. Добавил класс исключения

2017-02-15 16:16 UTC, BubuntuClu commented on app/controllers/users_controller.rb
> +    if request.patch? && params[:user]
избавился от проверки.

2017-02-16 09:40 UTC, vkurennov requested changes

2017-02-16 09:40 UTC, vkurennov commented on app/models/user.rb
> +  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
И почему не исправил?

2017-02-16 09:40 UTC, vkurennov commented on app/models/user.rb
> +  def send_email(params)
Слишком общее название метода. Что за email мы отправляем? Из названия не ясно. Нужно найти краткое и в то же время емкое название метода,  чтобы было сразу понятно, что конкретно он делает

2017-02-16 09:40 UTC, vkurennov commented on app/models/user.rb
> +            rescue NoMethodError
Вообще, использовать исключения для управления контролем исполнения кода не очень хорошо, т.к. обработка исключений довольно медленная. Лучше заменять на if/else, где это возможно. Например, проверить, есть ли у auth ключ или метод info и если нет, присвоить nil, а если есть, взять email.

2017-02-16 09:40 UTC, vkurennov commented on app/models/user.rb
> +    email = "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com" unless email
Используй `||=`. Из-за длинной строки unless теряется

2017-02-16 09:40 UTC, vkurennov commented on db/schema.rb
> +    t.string   "provider"
Хорошо бы составной индекс добавить на provider и uid.

2017-02-16 09:40 UTC, vkurennov commented on spec/acceptance/social_networks_sigh_in_spec.rb
> +    scenario 'without email' do
Нужен еще один сценарий: юзер заполнил email, письмо ушло, но юзер не кликнул по ссылке в письме и снова пытается залогиниться через ту же соц. сеть. У него не должно этого получиться.

2017-02-16 09:54 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
А, этот я пропустил. Это да, косяк

2017-02-16 09:55 UTC, BubuntuClu commented on db/schema.rb
> +    t.string   "provider"
Хм. Видел это в тексте задания, но почему-то я подумал что он уже добавлен и не стал проверять. Странное поведение)

2017-02-16 10:01 UTC, BubuntuClu commented on app/models/user.rb
> +  def send_email(params)
+

2017-02-16 10:05 UTC, BubuntuClu commented on app/models/user.rb
> +    email = "#{TEMP_EMAIL_PREFIX}-#{auth.uid}-#{auth.provider}.com" unless email
+

2017-02-16 10:06 UTC, BubuntuClu commented on app/models/user.rb
> +            rescue NoMethodError
+

2017-02-16 10:06 UTC, BubuntuClu commented on db/schema.rb
> +    t.string   "provider"
+

2017-02-16 10:22 UTC, BubuntuClu commented on spec/acceptance/social_networks_sigh_in_spec.rb
> +    scenario 'without email' do
+

2017-02-16 10:41 UTC, BubuntuClu commented on app/models/user.rb
> +  validates_format_of :email, :without => TEMP_EMAIL_REGEX, on: :update
Пересмотрел концепцию проверки почты. Заменил на проверку при отправке письма с подтверждением

2017-02-16 11:41 UTC, vkurennov approved these changes

2017-02-16 14:11 UTC, merged