Background job
BubuntuClu/questionTime pull request #26
Opened 2017-02-27 21:52 UTC by BubuntuClu

2017-02-28 09:15 UTC, vkurennov requested changes

2017-02-28 09:15 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :load_question, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe]
Вынеси подписку в отдельный ресурс и CRUD-опреации к нему

2017-02-28 09:15 UTC, vkurennov commented on app/jobs/answer_job.rb
> +    answer.question.subscribers.each do |user|
Надо использовать find_each

2017-02-28 09:15 UTC, vkurennov commented on app/models/question.rb
> +  def subscribe_user(user)
Переделай хранение подписчиков на отдельную модель и таблицу

2017-02-28 09:15 UTC, vkurennov commented on app/models/user.rb
> +    Question.find(question.id).subscribers.include?(id)
Зачем искать вопрос через find, если и так объект вопроса передается в метод?

2017-02-28 09:15 UTC, vkurennov commented on spec/jobs/answer_job_spec.rb
> +    not_subscribers.each do |not_subscriber|
Верно, но надо это разделить на 2 теста

2017-03-01 07:26 UTC, vkurennov requested changes

2017-03-01 07:26 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +  before_action :load_question, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe]
Теперь надо убрать здесь `:subscribe, :unsubscribe`

2017-03-01 07:26 UTC, vkurennov commented on app/models/question.rb
> +  has_many :subscribers, dependent: :destroy
Подписчик - это пользователь, а утебя не подписчики, а подписки, правильно было бы назвать модель Subscription. А через нее сделать ассоциацию `has_many :subscribers`, и вот subscribers - это бы и были юзеры-подписчики, потому что что такое `question.users` и чем они отличаются от `question.user` не понятно, а вот `question.subscribers` довольно однозначно понимается

2017-03-01 07:26 UTC, vkurennov commented on app/models/subscriber.rb
> +class Subscriber < ApplicationRecord
Переименуй в Subscription

2017-03-01 08:25 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +  before_action :load_question, only: [:show, :edit, :update, :destroy, :subscribe, :unsubscribe]
+

2017-03-01 12:42 UTC, vkurennov approved these changes

2017-03-01 12:42 UTC, vkurennov commented on app/views/questions/_subscribe.html.slim
> +- if current_user
Вместо вложенных if, используй составные условия (&&)

2017-03-01 14:42 UTC, merged