Search
BubuntuClu/questionTime pull request #27
Opened 2017-03-01 21:01 UTC by BubuntuClu

2017-03-02 07:28 UTC, vkurennov requested changes

2017-03-02 07:28 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +    if %w(question answer comment user).include?(params[:search_type])
Дублирование массива на 90% (без одного элемента). И вообще, массив лучше вынести в константу

2017-03-02 07:28 UTC, vkurennov commented on app/views/searches/_search.html.slim
> +    = select_tag :search_type, options_for_select(['question','answer','comment','user','all'])
опять тот же массив, дублирование уже в 3-й раз

2017-03-02 07:28 UTC, vkurennov commented on spec/acceptance/search_spec.rb
> +    before(:all) do
Индексация не работает по той же причине, почему и для js-тестов мы должны отключать в настройках фикстуры: по-умолчанию, данные в базе не создаются и из внешнего процесса, под которым работает поиск, данные не доступны. Тут надо так же как и в js-тестах отключать фикстуры и работать через DatabaseCleaner. Самое простое - обозначить все тесты поиска как `js: true`

2017-03-02 07:28 UTC, vkurennov commented on spec/acceptance/search_spec.rb
> +    scenario 'try to find question' do
А тест с поиском all?

2017-03-02 07:28 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +    return [] unless %w(question answer comment user all).include?(params[:search_type])
Всю эту логику стоит вынести в отдельный класс, т.к. это не задача контроллера. А здесь просто вызывать класс, передавая ему нужные параметры.

2017-03-02 07:28 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +      @results = params[:search_type].classify.constantize.search(params[:search]).page(params[:page]).per(10)
строку поиска надо эскейпировать, т.к. там могут быть управляющие символы, например, `@`. См. документацию ThinkingSphinx

2017-03-02 11:44 UTC, vkurennov requested changes

2017-03-02 11:44 UTC, vkurennov commented on app/helpers/searcher_helper.rb
> +  TYPES = %w(question answer comment user all).freeze
Лучше было бы вынести в константу класса Searcher

2017-03-02 11:44 UTC, vkurennov commented on app/services/searcher.rb
> +class Searcher < ActiveRecord::Base
1. Этот класс не имеет таблицы за собой, поэтому он не должен быть наследником AR::Base. Это простой руби-класс
2. Лучше назвать его просто Search

2017-03-02 11:44 UTC, vkurennov commented on app/services/searcher.rb
> +  def self.call(type, search, page)
Обыно метод называют run.

2017-03-02 11:44 UTC, vkurennov commented on app/services/searcher.rb
> +    types = ApplicationController.helpers.get_types
Плохо. Модели ничего не должны знать об уровне контроллеров. Лучше просто поместить константу с типами прямо в этот класс. В видах их как раз можно использовать, будет `Search::TYPES`, понятно и логично.

2017-03-02 11:44 UTC, vkurennov commented on app/services/searcher.rb
> +      @results = type.classify.constantize.search(request).page(page).per(PER)
Зачем тут инстанс-переменная, да еще и на уровне класса?

2017-03-02 11:44 UTC, vkurennov commented on spec/controllers/searchers_controller_spec.rb
> +    it 'invalid params' do
Тут достаточно проверить вызов метода у класса поиска с нужными параметрами (message expectations)

2017-03-02 11:44 UTC, vkurennov commented on app/services/searcher.rb
> +class Searcher < ActiveRecord::Base
А где тесты на этот класс?

2017-03-02 12:13 UTC, BubuntuClu commented on app/services/searcher.rb
> +    types = ApplicationController.helpers.get_types
у меня изначально так и было. но доступ из вьюхи я не смог получить к константе

2017-03-02 12:17 UTC, BubuntuClu commented on app/services/searcher.rb
> +      @results = type.classify.constantize.search(request).page(page).per(PER)
+

2017-03-02 12:17 UTC, BubuntuClu commented on app/services/searcher.rb
> +    types = ApplicationController.helpers.get_types
+

2017-03-02 12:17 UTC, BubuntuClu commented on app/services/searcher.rb
> +  def self.call(type, search, page)
+

2017-03-02 12:17 UTC, BubuntuClu commented on app/services/searcher.rb
> +class Searcher < ActiveRecord::Base
+

2017-03-02 12:17 UTC, BubuntuClu commented on app/helpers/searcher_helper.rb
> +  TYPES = %w(question answer comment user all).freeze
+

2017-03-02 12:18 UTC, BubuntuClu commented
Я так и хотел изначально сделать, все в классе Searcher, но у меня не было доступа к константе(почему-то), поэтому извратился через хелпер

2017-03-02 12:50 UTC, BubuntuClu commented on spec/services/search_service_spec.rb
> +RSpec.describe Search do
не совсем понимаю как тестировать этот класс. для него тоже надо объекты создавать и индексировать?

2017-03-03 06:42 UTC, vkurennov requested changes

2017-03-03 06:42 UTC, vkurennov commented on spec/services/search_service_spec.rb
> +RSpec.describe Search do
Ну если тебе нужны его инстансы, то да. Но у тебя-то метод класса, поэтому инстансы не нужны

2017-03-03 06:42 UTC, vkurennov commented on spec/services/search_service_spec.rb
> +      expect(Search).to receive(:run).with('question', 'question', 0)
Это бессмысленный тест. Ты проверяешь то, что будет вызван метод run у класса Search и сам же и вызываешь этот тест. Так можно проверять, например, что 1 равно одному и другие интересные тесты писать, только это к делу отношения не имеет.

А проверять нужно, что метод **делает**, что вызывает, какие возврващет значения на разных входных данных и т.п.

2017-03-03 17:07 UTC, vkurennov approved these changes

2017-03-03 17:07 UTC, vkurennov commented on spec/services/search_service_spec.rb
> +    expect(Search::TYPES).to eq %w(question answer comment user all)
Это лишнее, нет смысла проверять значения констант, это ни на что не влияет

2017-03-03 17:07 UTC, vkurennov commented on spec/services/search_service_spec.rb
> +    expect(ThinkingSphinx::Query).to receive(:escape).with(request).and_call_original
Это тоже лишнее, достаточно проверить, что поиск вызывается с заэскейпленным запросом, что уже подтверждает факт, того, что эскейпинг был

2017-03-03 17:07 UTC, vkurennov commented on spec/services/search_service_spec.rb
> +RSpec.describe Search do
Еще нужен тест на то, когда возвращается пустой массив

2017-03-03 17:54 UTC, merged